# 本地服务器配置
LOCAL_IP=10.7.0.2
LOCAL_PRIVATE_KEY=aO0K5fNddN3tqAnYe+9BWW0/R8EW6jfmVNuLw1j7WEo=
LOCAL_PUBLIC_KEY=z3c55VFc9mB8CbG7P4siMfF2Glg2+aLLby/xxXEd0ko=
DEFAULT_GATEWAY=192.168.2.1
DEFAULT_INTERFACE=enp129s0f0
